### ISSUE TITLE
[Android Bootcamp] Pre-work - Review my app

### ISSUE THREAD

**Issue by wangwh03** [wangwh03/AndroidTraining#1] opened 2015-09-23 05:55 UTC
My app is complete, please review. Also, I was wondering if I added a few new (optional) features after this, can I request another review? Thanks a lot!  /cc @codepathreview @codepath

**Comment by nidhi1608** [comment] 2015-09-23 07:19
Sure, you can let us know here or create a new issue when toy have more updates.

**Comment by nidhi1608** [comment] 2015-09-27 20:20
Weihua,

Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

We are reviewing the submissions right now and will get in touch with you via email a few days after the submission closing date, October 2nd, 2015. In the mean time, you may consider working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and let us know if you have any questions.

You may update this issue when you have additional features.

**Comment by wangwh03** [comment] 2015-09-29 02:33
Thanks a lot Nidhi! I finished 2 more suggested features including:
- Improve style of the todo items in the list using a custom adapter
- Add support for completion due dates for todo items (and display within listview item)

I am working on the last suggested feature to use DialogFragment instead of new Activity for editing items, will update this issue again once finished.  

Please feel free to let me know if you see anything that can be improved in my code. Thanks a lot for your time and help!

/cc @codepathreview @codepath

**Comment by nidhi1608** [comment] 2015-09-29 17:44
Excellent progress Weihua. Nice to see you working on optionals. Since you still have a lot of time before the class starts, I would encourage you to play around with the app a bit more after you finish all of the optionals. You may benchmark a couple of popular todo apps on the play store and go from there. Mobile is all about adding minor details and UI polish to your app. Thats what takes an app to the next level. Hope you're having fun building an actual app from scratch.

**Comment by wangwh03** [comment] 2015-10-02 02:53
Nidhi, thanks a lot for your suggestions! I finished the last suggested optional feature to edit in an overlay, will take a look at polishing UI now. Thanks a lot for your time and help!

/cc @codepathreview @codepath

**Comment by wangwh03** [comment] 2015-10-03 05:07
Added a little Groupon green style for button, title, and text editor.  The app does not handle exceptions properly yet, will keep improving error handling and styles.

Thanks,
Weihua

/cc @codepathreview @codepath

**Closed as completed** 2015-10-27 02:11 UTC
